spring.application.name=msproveedor
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/db_proveedor?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

ms.productos.url=http://localhost:8082/api/productos/
ms.inventario.ajuste.url=http://localhost:8082/api/inventario/ajustar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect